version: '3.8'

services:
  vcall-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vcall-app
    ports:
      - "8008:80"
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
